export default {
  materials: [
    { code: 'C',  name: 'carbon', rarity: 'Very Common', score: 1 },
    { code: 'Fe', name: 'iron', rarity: 'Very Common', score: 1 },
    { code: 'Ni', name: 'nickel', rarity: 'Very Common', score: 1 },
    { code: 'P',  name: 'phosphorus', rarity: 'Very Common', score: 1 },
    { code: 'S',  name: 'sulphur', rarity: 'Very Common', score: 1 },
    { code: 'As', name: 'arsenic', rarity: 'Common', score: 2 },
    { code: 'Cr', name: 'chromium', rarity: 'Common', score: 2 },
    { code: 'Ge', name: 'germanium', rarity: 'Common', score: 2 },
    { code: 'Mn', name: 'manganese', rarity: 'Common', score: 2 },
    { code: 'Se', name: 'selenium', rarity: 'Common', score: 2 },
    { code: 'V',  name: 'vanadium', rarity: 'Common', score: 2 },
    { code: 'Zn', name: 'zinc', rarity: 'Common', score: 2 },
    { code: 'Zr', name: 'zirconium', rarity: 'Common', score: 2 },
    { code: 'Cd', name: 'cadmium', rarity: 'Rare', score: 3 },
    { code: 'Hg', name: 'mercury', rarity: 'Rare', score: 3 },
    { code: 'Mo', name: 'molybdenum', rarity: 'Rare', score: 3 },
    { code: 'Nb', name: 'niobium', rarity: 'Rare', score: 3 },
    { code: 'Sn', name: 'tin', rarity: 'Rare', score: 3 },
    { code: 'W',  name: 'tungsten', rarity: 'Rare', score: 3 },
    { code: 'Sb', name: 'antimony', rarity: 'Very Rare', score: 4 },
    { code: 'Po', name: 'polonium', rarity: 'Very Rare', score: 4 },
    { code: 'Ru', name: 'ruthenium', rarity: 'Very Rare', score: 4 },
    { code: 'Tc', name: 'technetium', rarity: 'Very Rare', score: 4 },
    { code: 'Te', name: 'tellurium', rarity: 'Very Rare', score: 4 },
    { code: 'Y',  name: 'yttrium', rarity: 'Very Rare', score: 4 },
  ],
};

