import DS from 'ember-data';

export default DS.Model.extend({
  world:       DS.belongsTo('world'),
  updater:     DS.attr('boolean'),
  surveyed_by: DS.attr("array"),
  updaters:    DS.attr("array"),
  carbon:      DS.attr('boolean'),
  iron:        DS.attr('boolean'),
  nickel:      DS.attr('boolean'),
  phosphorus:  DS.attr('boolean'),
  sulphur:     DS.attr('boolean'),
  arsenic:     DS.attr('boolean'),
  chromium:    DS.attr('boolean'),
  germanium:   DS.attr('boolean'),
  manganese:   DS.attr('boolean'),
  selenium:    DS.attr('boolean'),
  vanadium:    DS.attr('boolean'),
  zinc:        DS.attr('boolean'),
  zirconium:   DS.attr('boolean'),
  cadmium:     DS.attr('boolean'),
  mercury:     DS.attr('boolean'),
  molybdenum:  DS.attr('boolean'),
  niobium:     DS.attr('boolean'),
  tin:         DS.attr('boolean'),
  tungsten:    DS.attr('boolean'),
  antimony:    DS.attr('boolean'),
  polonium:    DS.attr('boolean'),
  ruthenium:   DS.attr('boolean'),
  technetium:  DS.attr('boolean'),
  tellurium:   DS.attr('boolean'),
  yttrium:     DS.attr('boolean'),
  created_at:  DS.attr('date'),
  updated_at:  DS.attr('date'),
  creator:     DS.attr('string')
});
